In [4]:
import yfinance as yf
import pandas as pd 
import numpy as np
dat = yf.Ticker("MSFT")

In [25]:

x =yf.download("MSFT", period="", progress=False)
x.T

Date             2026-02-06
Price  Ticker
Close  MSFT    4.011400e+02
High   MSFT    4.017900e+02
Low    MSFT    3.929200e+02
Open   MSFT    3.991700e+02
Volume MSFT    5.340360e+07

In [70]:
csv_path = "/home/dev/projects/Portfoliodrift/data/Portfolio - Copy.csv"

In [ ]:
prices_df = pd.read_csv(csv_path)
prices_df.head()

['Ticker', 'Quantity', 'Sector', 'Close', 'Weight']

In [91]:
prices_df

   Ticker  Quantity                Sector       Close     Weight
0    AAPL         1                    IT  218.270004   3.461290
1    ADAP         1       Pharmaceuticals    0.291000   0.004615
2    AGCO         1           Agriculture   93.089996   1.476206
3      BA         2  Military Engineering  178.110001   2.824439
4      BG         4           Agriculture   73.250000   1.161586
5    CALM         5           Agriculture   89.199997   1.414519
6     CAT         1           Engineering  335.779999   5.324744
7    CSCO         5                    IT   60.299999   0.956227
8     CVX         2     Natural Resources  164.750000   2.612578
9    DDOG         5                    IT  105.029999   1.665548
10     DE         4           Agriculture  472.429993   7.491717
11   GRWG         2           Agriculture    1.270000   0.020139
12    HUM         1            Healthcare  266.170013   4.220880
13   IBKR         1               Finance  173.360001   2.749114
14    IEX         5           Engineering  181.910004   2.884699
15    JPM         5               Finance  241.630005   3.831729
16     KO         5      Food & Beverages   68.669998   1.088958
17    LMT         5  Military Engineering  439.700012   6.972690
18     MS         1               Finance  120.139999   1.905160
19   MSCI         1               Finance  562.559998   8.920984
20   MSFT         3                    IT  391.260010   6.204537
21   NFLX         1         Entertainment  960.289978  15.228120
22    OSK         3           Engineering   95.779999   1.518863
23    PFE         2       Pharmaceuticals   26.280001   0.416744
24     PG         2        Consumer Goods  166.690002   2.643343
25    SPY         3               Finance  563.979980   8.943502
26   TMUS         5    Telecommunications  255.839996   4.057068

In [72]:
prices = yf.download(prices_df['Ticker'].tolist(), period="1y", progress=False)
prices.head()

portfolio_data = prices_df.copy()
if 'Adj Close' in prices.columns:
            prices_close = prices['Adj Close']
elif 'Close' in prices.columns:
            prices_close = prices['Close']
else:
    try:
        prices_close = prices.xs('Close', level=0, axis=1)
    except KeyError:
        prices_close = prices.xs('Adj Close', level=0, axis=1)

$ADAP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['ADAP']: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")

In [73]:
prices.dropna(axis=1, how='all')
prices.head()

Price      Adj Close       Close                                          \
Ticker          ADAP        AAPL ADAP        AGCO          BA         BG
Date
2025-02-13       NaN  240.481873  NaN   93.091232  185.440002  67.432907
2025-02-14       NaN  243.538574  NaN   97.257286  184.419998  68.118919
2025-02-18       NaN  243.409119  NaN  100.709137  184.970001  68.177460
2025-02-19       NaN  243.807358  NaN  101.988708  186.149994  68.470146
2025-02-20       NaN  244.763214  NaN  100.917442  180.880005  69.523842

Price                                                     ...   Volume  \
Ticker           CALM         CAT       CSCO         CVX  ...      LMT
Date                                                      ...
2025-02-13  99.978355  348.899261  62.325661  148.974030  ...  2400000
2025-02-14  87.550110  348.524414  63.331230  150.104599  ...  3252800
2025-02-18  83.738785  349.195221  63.057865  150.896973  ...  2812500
2025-02-19  84.733040  348.208771  63.301941  151.930893  ...  2802100
2025-02-20  82.956261  344.410980  63.135975  153.438324  ...  1358000

Price                                                                        \
Ticker           MS    MSCI      MSFT      NFLX     OSK       PFE        PG
Date
2025-02-13  4699800  784500  23891700  34761000  573700  30612500   6328300
2025-02-14  5044500  453900  22758500  31454000  587100  33214600  13179500
2025-02-18  3797000  748200  21423100  42293000  696800  40499700   7075300
2025-02-19  3623100  609000  24114200  26000000  556000  37292400   7910700
2025-02-20  8860800  737000  23508700  31118000  741100  37139000   6162600

Price
Ticker           SPY     TMUS
Date
2025-02-13  40921300  3859900
2025-02-14  26910400  4835300
2025-02-18  26749000  3879300
2025-02-19  31011100  3787700
2025-02-20  36554000  2794700

[5 rows x 136 columns]

In [87]:
valid = prices.columns.tolist()
valid[1][1]
tickers = prices.columns.get_level_values('Ticker').unique().tolist()
tickers

['ADAP',
 'AAPL',
 'AGCO',
 'BA',
 'BG',
 'CALM',
 'CAT',
 'CSCO',
 'CVX',
 'DDOG',
 'DE',
 'GRWG',
 'HUM',
 'IBKR',
 'IEX',
 'JPM',
 'KO',
 'LMT',
 'MS',
 'MSCI',
 'MSFT',
 'NFLX',
 'OSK',
 'PFE',
 'PG',
 'SPY',
 'TMUS']

In [75]:
print(prices.head())

Price      Adj Close       Close                                          \
Ticker          ADAP        AAPL ADAP        AGCO          BA         BG
Date
2025-02-13       NaN  240.481873  NaN   93.091232  185.440002  67.432907
2025-02-14       NaN  243.538574  NaN   97.257286  184.419998  68.118919
2025-02-18       NaN  243.409119  NaN  100.709137  184.970001  68.177460
2025-02-19       NaN  243.807358  NaN  101.988708  186.149994  68.470146
2025-02-20       NaN  244.763214  NaN  100.917442  180.880005  69.523842

Price                                                     ...   Volume  \
Ticker           CALM         CAT       CSCO         CVX  ...      LMT
Date                                                      ...
2025-02-13  99.978355  348.899261  62.325661  148.974030  ...  2400000
2025-02-14  87.550110  348.524414  63.331230  150.104599  ...  3252800
2025-02-18  83.738785  349.195221  63.057865  150.896973  ...  2812500
2025-02-19  84.733040  348.208771  63.301941  151.930893  ...  2802100
2025-02-20  82.956261  344.410980  63.135975  153.438324  ...  1358000

Price                                                                        \
Ticker           MS    MSCI      MSFT      NFLX     OSK       PFE        PG
Date
2025-02-13  4699800  784500  23891700  34761000  573700  30612500   6328300
2025-02-14  5044500  453900  22758500  31454000  587100  33214600  13179500
2025-02-18  3797000  748200  21423100  42293000  696800  40499700   7075300
2025-02-19  3623100  609000  24114200  26000000  556000  37292400   7910700
2025-02-20  8860800  737000  23508700  31118000  741100  37139000   6162600

Price
Ticker           SPY     TMUS
Date
2025-02-13  40921300  3859900
2025-02-14  26910400  4835300
2025-02-18  26749000  3879300
2025-02-19  31011100  3787700
2025-02-20  36554000  2794700

[5 rows x 136 columns]

In [76]:
print(prices.columns)

MultiIndex([('Adj Close', 'ADAP'),
            (    'Close', 'AAPL'),
            (    'Close', 'ADAP'),
            (    'Close', 'AGCO'),
            (    'Close',   'BA'),
            (    'Close',   'BG'),
            (    'Close', 'CALM'),
            (    'Close',  'CAT'),
            (    'Close', 'CSCO'),
            (    'Close',  'CVX'),
            ...
            (   'Volume',  'LMT'),
            (   'Volume',   'MS'),
            (   'Volume', 'MSCI'),
            (   'Volume', 'MSFT'),
            (   'Volume', 'NFLX'),
            (   'Volume',  'OSK'),
            (   'Volume',  'PFE'),
            (   'Volume',   'PG'),
            (   'Volume',  'SPY'),
            (   'Volume', 'TMUS')],
           names=['Price', 'Ticker'], length=136)

In [79]:
tickers = prices.columns.get_level_values('Ticker').unique().tolist()
weights = portfolio_data['Weight'].tolist()
s = pd.Series(weights, index=portfolio_data['Ticker'].tolist())
s

AAPL     3.461290
ADAP     0.004615
AGCO     1.476206
BA       2.824439
BG       1.161586
CALM     1.414519
CAT      5.324744
CSCO     0.956227
CVX      2.612578
DDOG     1.665548
DE       7.491717
GRWG     0.020139
HUM      4.220880
IBKR     2.749114
IEX      2.884699
JPM      3.831729
KO       1.088958
LMT      6.972690
MS       1.905160
MSCI     8.920984
MSFT     6.204537
NFLX    15.228120
OSK      1.518863
PFE      0.416744
PG       2.643343
SPY      8.943502
TMUS     4.057068
dtype: float64

In [97]:
tickers = [col[1] if isinstance(col, tuple) else col for col in valid]
align = s[tickers]
align

ADAP    0.004615
AAPL    3.461290
ADAP    0.004615
AGCO    1.476206
BA      2.824439
          ...
OSK     1.518863
PFE     0.416744
PG      2.643343
SPY     8.943502
TMUS    4.057068
Length: 136, dtype: float64

In [99]:
align = align / align.sum()
align

ADAP    0.000009
AAPL    0.006923
ADAP    0.000009
AGCO    0.002952
BA      0.005649
          ...
OSK     0.003038
PFE     0.000833
PG      0.005287
SPY     0.017887
TMUS    0.008114
Length: 136, dtype: float64

In [33]:
total = csv["Weight"].sum()
print(total)
x = 0.0
for i in csv["Weight"]:
   x += i
print(x)

1.0
1.0

In [58]:
tickers = csv["Ticker"].tolist()
tickers

['AAPL', 'MSFT', 'VTI', 'BTC-USD']

In [78]:
prices_df = yf.download(tickers, period="1y", progress=False)
prices_df.dropna().head()

Price            Close                                              High  \
Ticker            AAPL       BTC-USD        MSFT         VTI        AAPL
Date
2025-02-10  226.874191  97437.554688  409.201416  296.293304  229.804175
2025-02-11  231.827271  95747.429688  408.427124  296.135223  234.428377
2025-02-12  236.062775  97885.859375  406.044708  295.157166  236.152480
2025-02-13  240.706879  96623.867188  407.533722  298.239532  241.514116
2025-02-14  243.766464  97508.968750  405.439148  298.200012  244.713224

Price                                                    Low                \
Ticker           BTC-USD        MSFT         VTI        AAPL       BTC-USD
Date
2025-02-10  98333.218750  412.417681  296.609453  226.425728  95320.843750
2025-02-11  98492.898438  409.469423  296.451372  227.352581  94875.039062
2025-02-12  98151.023438  407.742178  295.720269  229.893867  94101.203125
2025-02-13  98111.085938  407.990345  298.328444  234.767199  95269.710938
2025-02-14  98819.468750  405.915644  298.901442  240.168766  96342.804688

Price                                     Open                            \
Ticker            MSFT         VTI        AAPL       BTC-USD        MSFT
Date
2025-02-10  407.910948  295.305364  228.787662  96499.460938  410.680495
2025-02-11  406.302780  295.078120  227.422335  97438.132812  406.640317
2025-02-12  401.408892  292.667536  230.412099  95745.695312  404.228092
2025-02-13  403.384308  295.176910  236.102628  97888.750000  404.019636
2025-02-14  402.907833  297.864116  240.427874  96623.367188  404.803850

Price                       Volume
Ticker             VTI        AAPL       BTC-USD        MSFT        VTI
Date
2025-02-10  295.947519  33115600.0  4.007896e+10  20817900.0  2623900.0
2025-02-11  295.127535  53718400.0  3.748878e+10  18140600.0  2719900.0
2025-02-12  293.299832  45243300.0  4.934045e+10  19121700.0  3283500.0
2025-02-13  295.907977  53614100.0  3.714728e+10  23891700.0  3066800.0
2025-02-14  298.358086  40896200.0  3.269799e+10  22758500.0  2377000.0

In [83]:
returns = np.log(prices_df).diff().dropna()
returns

Price          Close                                    High            \
Ticker          AAPL   BTC-USD      MSFT       VTI      AAPL   BTC-USD
Date
2025-02-11  0.021597 -0.017498 -0.001894 -0.000534  0.019923  0.001623
2025-02-12  0.018105  0.022088 -0.005850 -0.003308  0.007328 -0.003477
2025-02-13  0.019482 -0.012976  0.003660  0.010389  0.022450 -0.000407
2025-02-14  0.012631  0.009119 -0.005153 -0.000133  0.013159  0.007194
2025-02-19  0.001635  0.011407  0.012445  0.001420  0.003379  0.001656
...              ...       ...       ...       ...       ...       ...
2026-01-30  0.004635 -0.005133 -0.007432 -0.005038  0.008628 -0.052930
2026-02-03 -0.001965 -0.039600 -0.029142 -0.007709  0.005126 -0.001765
2026-02-04  0.025680 -0.035171  0.007221 -0.004719  0.025672 -0.028905
2026-02-05 -0.002100 -0.152334 -0.050812 -0.012944  0.001970 -0.049376
2026-02-06  0.007978  0.118003  0.018798  0.020924  0.005032 -0.020440

Price                                Low                                \
Ticker          MSFT       VTI      AAPL   BTC-USD      MSFT       VTI
Date
2025-02-11 -0.007174 -0.000533  0.004085 -0.004688 -0.003950 -0.000770
2025-02-12 -0.004227 -0.002469  0.011116 -0.008190 -0.012118 -0.008203
2025-02-13  0.000608  0.008781  0.020977  0.012341  0.004909  0.008538
2025-02-14 -0.005098  0.001919  0.022747  0.011201 -0.001182  0.009063
2025-02-19  0.011839  0.002277  0.005443  0.017231  0.002825  0.001526
...              ...       ...       ...       ...       ...       ...
2026-01-30 -0.006575 -0.005220 -0.008804 -0.026524  0.012815  0.001982
2026-02-03 -0.020381  0.000320  0.031892 -0.022439 -0.032959 -0.007629
2026-02-04 -0.005345 -0.007189  0.017337 -0.015445  0.001663 -0.002913
2026-02-05 -0.027776 -0.010941  0.003446 -0.140785 -0.042224 -0.008190
2026-02-06 -0.016073  0.013168  0.013451 -0.037240  0.001528  0.008309

Price           Open                                  Volume            \
Ticker          AAPL   BTC-USD      MSFT       VTI      AAPL   BTC-USD
Date
2025-02-11 -0.005986  0.009680 -0.009886 -0.002775  0.483751 -0.066810
2025-02-12  0.013061 -0.017522 -0.005950 -0.006212 -0.171701  0.274702
2025-02-13  0.024397  0.022136 -0.000516  0.008853  0.169758 -0.283854
2025-02-14  0.018154 -0.013011  0.001939  0.008246 -0.270775 -0.127577
2025-02-19  0.002087 -0.002522 -0.000294 -0.001721 -0.416094 -0.252702
...              ...       ...       ...       ...       ...       ...
2026-01-30 -0.011030 -0.053049 -0.001865 -0.008037  0.318135  0.108794
2026-02-03  0.034658  0.022160 -0.019314  0.010168 -0.137863 -0.096196
2026-02-04  0.011413 -0.039574 -0.026436 -0.007726  0.340823 -0.015263
2026-02-05  0.021221 -0.035303 -0.008700 -0.013428 -0.535989  0.624479
2026-02-06 -0.003638 -0.152251 -0.020506  0.000685 -0.049464 -0.090285

Price
Ticker          MSFT       VTI
Date
2025-02-11 -0.137661  0.035933
2025-02-12  0.052671  0.188315
2025-02-13  0.222707 -0.068275
2025-02-14 -0.048592 -0.254795
2025-02-19  0.118331 -0.105263
...              ...       ...
2026-01-30 -0.788522  0.102932
2026-02-03  0.374911  0.408134
2026-02-04 -0.310864 -0.009693
2026-02-05  0.387089 -0.015159
2026-02-06 -0.216149 -0.551898

[194 rows x 20 columns]

In [ ]:
returns = prices_df

In [36]:
stocks = "SPY NVDA GOOG AMZN ".split()
stocks

['SPY', 'NVDA', 'GOOG', 'AMZN']

In [37]:
data = yf.download(stocks, "2025-10-21")["Close"]

[*********************100%***********************]  4 of 4 completed

In [38]:
returns = np.log(data).diff().dropna()
returns.head()

Ticker          AMZN      GOOG      NVDA       SPY
Date
2025-10-22 -0.018547  0.004723 -0.004869 -0.005212
2025-10-23  0.014304  0.004741  0.010374  0.005912
2025-10-24  0.014013  0.026371  0.022258  0.008139
2025-10-27  0.012235  0.035521  0.027692  0.011729
2025-10-28  0.009995 -0.005572  0.048619  0.002652

### covariance and variance

In [48]:
cov = returns.cov() * 252

simple weighted variance

In [49]:
np.sqrt(returns.var() *252)

Ticker
AMZN    0.342518
GOOG    0.274952
NVDA    0.374496
SPY     0.119803
dtype: float64

In [50]:
(returns.var() * 252) ** .5

Ticker
AMZN    0.342518
GOOG    0.274952
NVDA    0.374496
SPY     0.119803
dtype: float64

In [51]:
weights = np.array([ .1, .1, .3, .4])
np.sqrt(np.dot(weights, returns.var())*252)

np.float64(0.2590499638531393)

portfolio variance

In [53]:
var = np.dot(weights.T, np.dot(weights, cov))
var

np.float64(0.031367383271134135)

In [41]:
returns.var()

Ticker
AMZN    0.000466
GOOG    0.000300
NVDA    0.000557
SPY     0.000057
dtype: float64

portfolio volatility

In [ ]:
std = np.sqrt(var)
std